[env:sensecap_d1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi

upload_speed = 460800
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM

lib_deps =
    moononournation/Arduino_GFX_Library @ ^1.4.9
    hideakitai/PCA95x5
